function Hd = getFilterCheb1
%GETFILTERCHEB1 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 26-Mar-2017 15:14:23

% Chebyshev Type I Highpass filter designed using FDESIGN.HIGHPASS.

% All frequency values are in kHz.
Fs = 100e3;  % Sampling Frequency

Fstop = 15e3;          % Stopband Frequency
Fpass = 35e3;          % Passband Frequency
Astop = 40;          % Stopband Attenuation (dB)
Apass = 2;           % Passband Ripple (dB)
match = 'passband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY1 method.
h  = fdesign.highpass(Fstop, Fpass, Astop, Apass, Fs);
Hd = design(h, 'cheby1', 'MatchExactly', match);

% [EOF]
