function Hd = getFilterElliptic
%GETFILTERELLIPTIC Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 26-Mar-2017 15:17:14

% Elliptic Bandpass filter designed using FDESIGN.BANDPASS.

% All frequency values are in kHz.
Fs = 100e3;  % Sampling Frequency

Fstop1 = 15e3;      % First Stopband Frequency
Fpass1 = 20e3;      % First Passband Frequency
Fpass2 = 30e3;      % Second Passband Frequency
Fstop2 = 35e3;      % Second Stopband Frequency
Astop1 = 50;      % First Stopband Attenuation (dB)
Apass  = 5;       % Passband Ripple (dB)
Astop2 = 50;      % Second Stopband Attenuation (dB)
match  = 'both';  % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.bandpass(Fstop1, Fpass1, Fpass2, Fstop2, Astop1, Apass, ...
                      Astop2, Fs);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
