function Hd = getFilterCheb2
%GETFILTERCHEB2 Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 26-Mar-2017 15:16:06

% Chebyshev Type II Bandstop filter designed using FDESIGN.BANDSTOP.

% All frequency values are in kHz.
Fs = 100e3;  % Sampling Frequency

Fpass1 = 5e3;           % First Passband Frequency
Fstop1 = 15e3;          % First Stopband Frequency
Fstop2 = 35e3;          % Second Stopband Frequency
Fpass2 = 45e3;          % Second Passband Frequency
Apass1 = 5;           % First Passband Ripple (dB)
Astop  = 50;          % Stopband Attenuation (dB)
Apass2 = 5;           % Second Passband Ripple (dB)
match  = 'stopband';  % Band to match exactly

% Construct an FDESIGN object and call its CHEBY2 method.
h  = fdesign.bandstop(Fpass1, Fstop1, Fstop2, Fpass2, Apass1, Astop, ...
                      Apass2, Fs);
Hd = design(h, 'cheby2', 'MatchExactly', match);

% [EOF]
