function Hd = Butter1
%GETFILTER Returns a discrete-time filter System object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the DSP System Toolbox 9.3.
% Generated on: 12-Nov-2017 15:20:44

Fpass = 2500;   % Passband Frequency
Fstop = 4000;   % Stopband Frequency
Apass = 3;      % Passband Ripple (dB)
Astop = 55;     % Stopband Attenuation (dB)
Fs    = 44100;  % Sampling Frequency

h = fdesign.lowpass('fp,fst,ap,ast', Fpass, Fstop, Apass, Astop, Fs);

Hd = design(h, 'butter', ...
    'FilterStructure', 'df1sos', ...
    'MatchExactly', 'stopband', ...
    'SOSScaleNorm', 'Linf', ...
    'SystemObject', true);


