function Hd = getFilterIIR(a)
%GETFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.1 and the Signal Processing Toolbox 7.3.
% Generated on: 02-Oct-2017 15:22:43

% Elliptic Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are normalized to 1.

Fpass = 1/a;  % Passband Frequency
Fstop = 1.2/a;   % Stopband Frequency
Apass = 0.01;       % Passband Ripple (dB)
Astop = 75;        % Stopband Attenuation (dB)
match = 'both';    % Band to match exactly

% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(Fpass, Fstop, Apass, Astop);
Hd = design(h, 'ellip', 'MatchExactly', match);

% [EOF]
